name: Confirm Pull Request

on:
  pull_request:

concurrency: test

jobs:
  tests:
    name: Conduct tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
