name: Node.js Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # You need a shallow clone for GitVersion to work.
      # That's done specifying fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      # Install GitVersion to automatically create a semantic
      # version from your repository:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      # Run GitVersion (set an ID to later fetch values)
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      # Now  happens the magic where you set the id of your package the default
      # would be $GITVERSION_SEMVER. But you could also use teh tag name
      # or access individual values from the gitversion task:
      - name: 'Change NPM version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: $GITVERSION_SEMVER
          # Use the tag name: version: ${{github.event.release.tag_name}}
          # Access individual values from gitversion:
          # ${{ steps.gitversion.outputs.major }}


      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
